name: Build Android APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set Build Number Environment Variable
      run: |
          echo "BUILD_NUMBER=$((${{ github.run_number }} - 5))" >> $GITHUB_ENV
          echo $BUILD_NUMBER

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: tempest.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Get the latest prefixed numeric tag
      id: get_latest_tag
      run: |
        git fetch --tags
        latest_tag=$(git tag | grep -E '^v[0-9]+$' | sort -V | tail -n 1)
        if [ -z "$latest_tag" ]; then
          new_tag=v1
        else
          new_tag=v$(( ${latest_tag#v} + 1 ))
        fi
        echo "::set-output name=new_tag::$new_tag"

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_latest_tag.outputs.new_tag }}
        release_name: Release ${{ steps.get_latest_tag.outputs.new_tag }}
        draft: false
        prerelease: false

    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/release/app-release-unsigned.apk
        asset_name: tempest.apk
        asset_content_type: application/vnd.android.package-archive